<?php
DEFINE('PROTOCOL_SECRET_KEY'	, 'sadade4safdgreadads' );
DEFINE('PROTOCOL_LENGTH_TYPE'	, 'n');
DEFINE('BASE_PROTOCOL'		, '\json_protocol');

//@此处可以进行协议编号的宏定义
//@登录相关
DEFINE("CS_PROTOCOL_P_LOGIN"		,1000);//@登录消息
DEFINE("CS_PROTOCOL_P_QUIT"		,1001);//@退出消息
DEFINE("CS_PROTOCOL_P_CREATE"		,1002);//@创建消息
DEFINE("CS_PROTOCOL_P_DATA"		,1004);//@玩家消息

DEFINE("CS_PROTOCOL_MANAGER_HANDPUSH"	,2001);//@手动push订单
DEFINE("CS_PROTOCOL_MANAGER_HANDRECH"	,2002);//@手动充值
DEFINE("CS_PROTOCOL_MANAGER_RESEND"	,2003);//@失败订单重新进入队列



//@聊天相关
DEFINE("CS_PROTOCOL_C_BROADCAST"	,9999);//@广播消息
DEFINE("CS_PROTOCOL_C_GUILD"		,9998);//@公会消息
DEFINE("CS_PROTOCOL_C_TEAM"		,9997);//@组队消息
DEFINE("CS_PROTOCOL_C_GROUPS"		,9996);//@群组消息
DEFINE("CS_PROTOCOL_C_WORLD"		,9995);//@世界消息
DEFINE("CS_PROTOCOL_C_SINGLE"		,9991);//@单人消息
?>
