<?php
DEFINE('SECRET_TEST_PAY_ENV',		0);

DEFINE('SECRET_HTTP_KEY'			,	'sdzxcas3wgdg5rasda'	);

//@百度
DEFINE('SECRET_BAIDU_APPID'			,	'8333168'	);
DEFINE('SECRET_BAIDU_APPKEY'		,	'0aMW8Tos38KOZyG5AtbvrEqC'	);
DEFINE('SECRET_BAIDU_SECRET'		,	'Scv25uvLnRlrawZLrlaFGu623Q97BXvZ'	);
DEFINE('SECRET_BAIDU_CHECK_IP'		,	'querysdkapi.91.com'	);
DEFINE('SECRET_BAIDU_CHECK_URI'		,	'/CpLoginStateQuery.ashx'	);

//@应用宝 需实现
DEFINE('SECRET_TENCENT_APPID'				,	'1105414767'	);
DEFINE('SECRET_TENCENT_APPKEY'				,	'ScGWDO4aRusKYdLc&'	);
DEFINE('SECRET_TENCENT_QQ_APPID'			,	'1105414767'	);
DEFINE('SECRET_TENCENT_QQ_APPKEY'			,	'ScGWDO4aRusKYdLc'	);
DEFINE('SECRET_TENCENT_WX_APPID'		,	'wxea9db1070a68cb13'	);
DEFINE('SECRET_TENCENT_WX_APPKEY'		,	'e653f4f2c40fcf51936219e8c4a50121'	);
if(SECRET_TEST_PAY_ENV)
	DEFINE('SECRET_TENCENT_CHECK_IP'		,	'ysdktest.qq.com'	);
else
	DEFINE('SECRET_TENCENT_CHECK_IP'		,	'ysdk.qq.com'   );
DEFINE('SECRET_TENCENT_QQ_CHECK_URI'		,	'/auth/qq_check_token'	);
DEFINE('SECRET_TENCENT_WX_CHECK_URI'		,	'/auth/wx_check_token'	);
if(SECRET_TEST_PAY_ENV)
{
	DEFINE('SECRET_TENCENT_PAY_IP'			,	'ysdktest.qq.com');//HTTPS
	DEFINE('SECRET_TENCENT_PAY_SECRET'		,	'2rFEMAuJw0tXmZZg31RfeWIV3qXMtp78&');//HTTPS
}
else
{
	DEFINE('SECRET_TENCENT_PAY_IP'			,	'ysdk.qq.com');//HTTPS
	DEFINE('SECRET_TENCENT_PAY_SECRET'		,	'pHA0jwf6TKP3bsKIQD46TYUGUd5N1rxc&');//HTTPS
}
DEFINE('SECRET_TENCENT_PAY_QUERY_URI'		,	'/mpay/get_balance_m');
DEFINE('SECRET_TENCENT_PAY_EXEC_URI'		,	'/mpay/pay_m');
DEFINE('SECRET_TENCENT_PAY_CANCEL_URI'		,	'/mpay/cancel_pay_m');




//@苹果
DEFINE('SECRET_IOS_APPKEY'			,	'xcasgg43asdadasdea'	);
DEFINE('SECRET_IOS_STATUS'			,	0	);

//@微信支付
DEFINE('SECRET_WINXIN_PAY_APPID'		,	'ASDASDADAA'	);
DEFINE('SECRET_WINXIN_PAY_MCHID'		,	'ASDASDADAA'	);
DEFINE('SECRET_WINXIN_PAY_APPKEY'		,	'&key=sdasadasdassss'	);
DEFINE('SECRET_WINXIN_PAY_SECRET'		,	'&key=sdasadasdassss'	);

//@qh360 //APPID and APPKEY and SECRET		OK
DEFINE('SECRET_360_APPID'			,	'203079051'	);
DEFINE('SECRET_360_APPKEY'			,	'70e9e672347c86a6cbd8244d8b47f03a'	);
DEFINE('SECRET_360_SECRET'			,	'#1ab3a4beb5bf4560b578131c750ae163'	);//开头#号不属于秘钥
DEFINE('SECRET_360_CHECK_IP'		,	'openapi.360.cn'	);
DEFINE('SECRET_360_CHECK_URI'		,	'/user/me.json'	);

//@发货来源
DEFINE('SECRET_INNER_ORIGIN'		,	0	);
DEFINE('SECRET_IOS_ORIGIN'			,	1	);
DEFINE('SECRET_WEIXIN_ORIGIN'		,	2	);
DEFINE('SECRET_BAIDU_ORIGIN'		,	3	);
DEFINE('SECRET_360_ORIGIN'			,	4	);
DEFINE('SECRET_ALBB_ORIGIN'			,	5	);
DEFINE('SECRET_UC_ORIGIN'			,	6	);
DEFINE('SECRET_TAOSHOUYOU_ORIGIN'	,	7	);
DEFINE('SECRET_MEIZU_ORIGIN'		,	8	);
DEFINE('SECRET_ANZHI_ORIGIN'		,	9	);
DEFINE('SECRET_VIVO_ORIGIN'			,	10	);
DEFINE('SECRET_HUAWEI_ORIGIN'		,	11	);
DEFINE('SECRET_HAIMA_ORIGIN'		,	12	);
DEFINE('SECRET_WANDOU_ORIGIN'		,	13	);
DEFINE('SECRET_DANGLE_ORIGIN'		,	14	);
DEFINE('SECRET_TENCET_ORIGIN'		,	15	);
DEFINE('SECRET_JINLI_ORIGIN'		,	16	);
DEFINE('SECRET_LESHI_ORIGIN'		,	17	);
DEFINE('SECRET_XIAOMI_ORIGIN'		,	18	);
DEFINE('SECRET_07073_ORIGIN'		,	19	);
DEFINE('SECRET_ANFENG_ORIGIN'		,	20	);
DEFINE('SECRET_LINYOU_ORIGIN'		,	21	);
DEFINE('SECRET_LENOVO_ORIGIN'		,	22	);
DEFINE('SECRET_TIANYOU_ORIGIN'		,	23	);
DEFINE('SECRET_OPPO_ORIGIN'			,	24	);
DEFINE('SECRET_YUWAN_ORIGIN'		,	25	);
DEFINE('SECRET_TIANYOU_PLATFORM_ORIGIN'	,	26);
DEFINE('SECRET_MOGELY_ORIGIN'			,	27	);
DEFINE('SECRET_XIAOYAO_ORIGIN'			,	28	);
DEFINE('SECRET_DIANYOU_ORIGIN'			,	29	);
DEFINE('SECRET_SHEDIAOYJZX_ORIGIN'		,	30	);
DEFINE('SECRET_TIANYOULJTX_ORIGIN'		,	31	);
DEFINE('SECRET_XIANQUHCZJ_ORIGIN'		,	32	);
DEFINE('SECRET_XIANQUCYJH_ORIGIN'		,	33	);
DEFINE('SECRET_KUPAI_ORIGIN'			,	34	);
DEFINE('SECRET_TIANYOUXMCQ_ORIGIN'		,	35	);
DEFINE('SECRET_TIANYOUXLJ3D_ORIGIN'		,	36	);
DEFINE('SECRET_GOOGLEPLAY_ORIGIN'		,	37	);
DEFINE('SECRET_TENCENT_ORIGIN'			,	38	);
DEFINE('SECRET_YUENANXLJ_ORIGIN'		,	39	);
DEFINE('SECRET_TAIQIQL_ORIGIN'			,	40	);
DEFINE('SECRET_ONESTORE_ORIGIN'			,	41	);
DEFINE('SECRET_WUYOUWANXQJ_ORIGIN'		,	42	);
DEFINE('SECRET_G265_ORIGIN'				,	43	);
DEFINE('SECRET_DIANZHI_ORIGIN'				,	44	);

//@UC九游 //APPID and APPKEY  rechargeOk loginCheckOk
DEFINE('SECRET_UC_APPID'			,	'724628'	);
DEFINE('SECRET_UC_APPKEY'			,	'840ad0a6412a7fd3065ce6f7bcce46d5'	);
DEFINE('SECRET_UC_SECRET'			,	'null'	);
DEFINE('SECRET_UC_TEST_STATUS'		,	1);
if(SECRET_TEST_PAY_ENV)
	DEFINE('SECRET_UC_CHECK_IP'		,	'sdk.test4.g.uc.cn');
else
	DEFINE('SECRET_UC_CHECK_IP'		,	'sdk.g.uc.cn');
DEFINE('SECRET_UC_CHECK_URI'		,	'/cp/account.verifySession');

//@淘手游 // OK  正式服 需要新参数
DEFINE('SECRET_TAOSHOUYOU_APPID'	,	'6e594c2f13f18cf119e28a87');
DEFINE('SECRET_TAOSHOUYOU_APPKEY'	,	'af449388e228acc6fdd90e1fe120ef94124ca497');
DEFINE('SECRET_TAOSHOUYOU_SECRET'	,	'af449388e228acc6fdd90e1fe120ef94124ca497');
DEFINE('SECRET_TAOSHOUYOU_CHECK_IP'	,	'sdk.taoshouyou.com');
DEFINE('SECRET_TAOSHOUYOU_CHECK_URI',	'/user/checktoken');

//@魅族 少参数 且需要实现订单签名
DEFINE('SECRET_MEIZU_APPID'			,	'3109840');
DEFINE('SECRET_MEIZU_APPKEY'		,	'1ead19ab6b6b486480fa543e4dae8085');
DEFINE('SECRET_MEIZU_SECRET'		,	':AdQfSWE462cBfpN2QPRDEVqbrMukxgTa');//开头:号不属于秘钥
DEFINE('SECRET_MEIZU_CHECK_IP'		,	'api.game.meizu.com');//@https
DEFINE('SECRET_MEIZU_CHECK_URI'		,	'/game/security/checksession');

//@无忧玩
DEFINE('SECRET_WUYOUWAN_APPID'			,	'73');
DEFINE('SECRET_WUYOUWAN_APPKEY'			,	'5D4B8A67B1C8A1B58B570040B4067A60');
DEFINE('SECRET_WUYOUWAN_SECRET'			,	'981A8778BE07717241C1559BF02407C2');
DEFINE('SECRET_WUYOUWAN_CHECK_IP'		,	'mapi.5uwan.com');
DEFINE('SECRET_WUYOUWAN_CHECK_URI'		,	'/Api/TokenCheck.ashx');


//@安智 // APPKEY and SECRET		OK
DEFINE('SECRET_ANZHI_APPID'			,	'null');
DEFINE('SECRET_ANZHI_APPKEY'		,	'1467012669P820sqkEgyQOq5YAdpWD');
DEFINE('SECRET_ANZHI_SECRET'		,	'Q1aGdBipC9jy6Q0xuOJBtez6');
DEFINE('SECRET_ANZHI_CHECK_IP'		,	'user.anzhi.com');
DEFINE('SECRET_ANZHI_CHECK_URI'		,	'/web/api/sdk/third/1/queryislogin');

//@步步高VIVO ok
DEFINE('SECRET_VIVO_CPID'			,	'20160614150917371968');
DEFINE('SECRET_VIVO_APPID'			,	'1a1b95c8c96a6529eae07534abe7b961');
DEFINE('SECRET_VIVO_APPKEY'			,	'572b37f33c8af0a9d2af0992e82a33c8');
DEFINE('SECRET_VIVO_SECRET'			,	'&'.md5('572b37f33c8af0a9d2af0992e82a33c8'));//开头&号不属于秘钥
DEFINE('SECRET_VIVO_CHECK_IP'		,	'usrsys.vivo.com.cn');//@https
DEFINE('SECRET_VIVO_CHECK_URI'		,	'/sdk/user/auth.do');
DEFINE('SECRET_VIVO_ORDER_IP'		,	'pay.vivo.com.cn'); // HTTPS //
DEFINE('SECRET_VIVO_ORDER_URI'		,	'/vcoin/trade');
DEFINE('SECRET_VIVO_NOTIFY_URL'		,	'http://'.MASTER_SERVER_IP.':8080/vivodelivery.xl');

//@酷派// ok 
DEFINE('SECRET_KUPAI_APPID'			,	'5000004013');
DEFINE('SECRET_KUPAI_APPKEY'		,	'a63244da8c1442de91fc8caee00fe644');
DEFINE('SECRET_KUPAI_SECRET'		,	'null');
DEFINE('SECRET_KUPAI_PUBKEY'		,	'kupai_rsa_public_key.pem');
DEFINE('SECRET_KUPAI_PRIKEY'		,	'kupai_rsa_private_key.pem');
DEFINE('SECRET_KUPAI_CHECK_IP'		,	'openapi.coolyun.com');//https get
DEFINE('SECRET_KUPAI_CHECK_URI'		,	'/oauth2/token');

//@华为 ok
DEFINE('SECRET_HUAWEI_CPID'			,	'890086000102020373');
DEFINE('SECRET_HUAWEI_APPID'		,	'10576189');
DEFINE('SECRET_HUAWEI_APPKEY'		,	'0b4ffefc512578ce93d36ac335770c0b');
DEFINE('SECRET_HUAWEI_SECRET'		,	'0b4ffefc512578ce93d36ac335770c0b');
DEFINE('SECRET_HUAWEI_PUBKEY'		,	'huawei_rsa_public_key.pem');
DEFINE('SECRET_HUAWEI_PRIKEY'		,	'huawei_rsa_private_key.pem');
DEFINE('SECRET_HUAWEI_CHECK_IP'		,	'api.vmall.com');//@https
DEFINE('SECRET_HUAWEI_CHECK_URI'	,	'/rest.php');

//@豌豆荚 ok
DEFINE('SECRET_WANDOU_APPID'		,	'100040798');
DEFINE('SECRET_WANDOU_APPKEY'		,	'078a3ec1a398dae48b650b81aa761687');
DEFINE('SECRET_WANDOU_SECRET'		,	'078a3ec1a398dae48b650b81aa761687');
DEFINE('SECRET_WANDOU_PUBKEY'		,	'wandou_rsa_public_key.pem');
DEFINE('SECRET_WANDOU_CHECK_IP'		,	'pay.wandoujia.com');//@https
DEFINE('SECRET_WANDOU_CHECK_URI'	,	'/api/uid/check');

//@当乐// appid and appkey 已OK
DEFINE('SECRET_DANGLE_APPID'		,	'6059');
DEFINE('SECRET_DANGLE_APPKEY'		,	'IcdWYz7m');
DEFINE('SECRET_DANGLE_SECRET'		,	'1cuk4Vd6MaOp');
DEFINE('SECRET_DANGLE_CHECK_IP'		,	'ngsdk.d.cn');//@GET
DEFINE('SECRET_DANGLE_CHECK_URI'	,	'/api/cp/checkToken');

//@乐视// appid and appkey and SECRET  OK
DEFINE('SECRET_LESHI_APPID'			,	'259880');
DEFINE('SECRET_LESHI_APPKEY'		,	'194ae65b821449a1ade3b55b5da119c1');
DEFINE('SECRET_LESHI_SECRET'		,	'88b087e306784e628a2d9ab5057aef9f');
DEFINE('SECRET_LESHI_CHECK_IP'		,	'sso.letv.com');//@https - GET
DEFINE('SECRET_LESHI_CHECK_URI'		,	'/oauthopen/userbasic');

//@金立//	ok
DEFINE('SECRET_JINLI_APPID'			,	'null');
DEFINE('SECRET_JINLI_APPKEY'		,	'7FD02853B8644A7BB8D255D064F73163');
DEFINE('SECRET_JINLI_SECRET'		,	'D259670E3B954F3C8DAA3B8D1F6F6134');
DEFINE('SECRET_JINLI_PUBKEY'		,	'jinli_rsa_public_key.pem');
DEFINE('SECRET_JINLI_PRIKEY'		,	'jinli_rsa_private_key.pem');
DEFINE('SECRET_JINLI_CHECK_IP'		,	'id.gionee.com');//@https
DEFINE('SECRET_JINLI_CHECK_URI'		,	'/account/verify.do');
DEFINE('SECRET_JINLI_ORDER_IP'		,	'pay.gionee.com');//@https
DEFINE('SECRET_JINLI_ORDER_URI'		,	'/order/create');
DEFINE('SECRET_JINLI_NOTIFY_URL'	,	'http://'.MASTER_SERVER_IP.':8080/jinlidelivery.xl');

//小米 ok
DEFINE('SECRET_XIAOMI_APPID'		,	'2882303761517485664');
DEFINE('SECRET_XIAOMI_APPKEY'		,	'5361748574664');
DEFINE('SECRET_XIAOMI_SECRET'		,	'VBB7JxrxZoxNQ0M7nAPlqQ==');
DEFINE('SECRET_XIAOMI_CHECK_IP'		,	'mis.migc.xiaomi.com');// GET
DEFINE('SECRET_XIAOMI_CHECK_URI'	,	'/api/biz/service/verifySession.do');

//OPPO ok
DEFINE('SECRET_OPPO_APPID'			,	'7356');
DEFINE('SECRET_OPPO_APPKEY'			,	'dCR8dYmfbj4GS0k0Gkk48COw0');
DEFINE('SECRET_OPPO_SECRET'			,	'b44E4F3841D7Ad8ed60a2311314Ff96f&');
DEFINE('SECRET_OPPO_PUBKEY'			,	'oppo_rsa_public_key.pem');
DEFINE('SECRET_OPPO_CHECK_IP'		,	'i.open.game.oppomobile.com');// GET
DEFINE('SECRET_OPPO_CHECK_URI'		,	'/gameopen/user/fileIdInfo');

//07073  OK
DEFINE('SECRET_07073_APPID'			,	'739');
DEFINE('SECRET_07073_APPKEY'		,	'769');
DEFINE('SECRET_07073_SECRET'		,	'C4D35374F1BB43DFF8F9EBFB476869');
DEFINE('SECRET_07073_CHECK_IP'		,	'sdk.07073sy.com');
DEFINE('SECRET_07073_CHECK_URI'		,	'/index.php/User/v4');

//联想  OK
DEFINE('SECRET_LENOVO_APPID'		,	'739');
DEFINE('SECRET_LENOVO_APPKEY'		,	'769');
DEFINE('SECRET_LENOVO_SECRET'		,	'C4D35374F1BB43DFF8F9EBFB476869');
DEFINE('SECRET_LENOVO_PRIKEY'		,	'lenovo_rsa_private_key.pem');
DEFINE('SECRET_LENOVO_CHECK_IP'		,	'passport.lenovo.com');//https//get
DEFINE('SECRET_LENOVO_CHECK_URI'	,	'/interserver/authen/1.2/getaccountid');

//安锋 ok
DEFINE('SECRET_ANFENG_APPID'		,	'1034');
DEFINE('SECRET_ANFENG_APPKEY'		,	'ca493299e52e7a3d3949fc8c9b595658');
DEFINE('SECRET_ANFENG_SECRET'		,	'ca493299e52e7a3d3949fc8c9b595658');
DEFINE('SECRET_ANFENG_PRIKEY'		,	'anfeng_rsa_private_key.pem');
DEFINE('SECRET_ANFENG_CHECK_IP'		,	'api.qcwan.com');
DEFINE('SECRET_ANFENG_CHECK_URI'	,	'/info/uc');

//麟游 ok
DEFINE('SECRET_LINYOU_APPID'		,	'xunlongjian');
DEFINE('SECRET_LINYOU_APPKEY'		,	'92481d79de7f7fcd');
DEFINE('SECRET_LINYOU_SECRET'		,	'1be6a7adfe5d71579a1e611407795dbe');
//DEFINE('SECRET_LINYOU_CHECK_IP'		,	'g.linnyou.com');
DEFINE('SECRET_LINYOU_CHECK_IP'		,	'lijinling.g.linnyou.com');
DEFINE('SECRET_LINYOU_CHECK_URI'	,	'/api/index');

//鱼丸 ok
DEFINE('SECRET_YUWAN_CPID'			,	'8699354291250762');
DEFINE('SECRET_YUWAN_APPID'			,	'264');
DEFINE('SECRET_YUWAN_APPKEY'		,	'39FDCDF61D11010BF497ED1CBD7774D86AFBB07A8636C5B0A35A08F2BEDF1879');
DEFINE('SECRET_YUWAN_SECRET'		,	'zdewsxrgmgjqbc4r');
DEFINE('SECRET_YUWAN_CHECK_IP'		,	'g.linnyou.com');
DEFINE('SECRET_YUWAN_CHECK_URI'		,	'/api/index');


//摩格乐游 ok
DEFINE('SECRET_MOGELY_GAMEID'		,	'228');
DEFINE('SECRET_MOGELY_APPID'		,	'223');
DEFINE('SECRET_MOGELY_APPKEY'		,	'06a2ed360381142ca92cdd4e4feb7f5d');
DEFINE('SECRET_MOGELY_SECRET'		,	'06a2ed360381142ca92cdd4e4feb7f5d');
DEFINE('SECRET_MOGELY_CHECK_IP'		,	'game.6y.com.cn');
DEFINE('SECRET_MOGELY_CHECK_URI'	,	'/sdk/islogin.php');

//@逍遥
DEFINE('SECRET_XIAOYAO_APPID'		,	'XY40853257');
DEFINE('SECRET_XIAOYAO_APPKEY'		,	'1aabb02d6d7be8167fa0025367aa6468');
DEFINE('SECRET_XIAOYAO_SECRET'		,	'028f859fa459b18d81426769f97f66d7');

//@点游
DEFINE('SECRET_DIANYOU_APPID'		,	'vZtwjt6U2fk=');
DEFINE('SECRET_DIANYOU_APPKEY'		,	'835163af96d8b821');
DEFINE('SECRET_DIANYOU_SECRET'		,	'MDAwMDAwMDA1NjZkMWEyNDAxNTY3MjBjMDEyZDAwMjQ=');
DEFINE('SECRET_DIANYOU_CHECK_IP'	,	'42.51.172.15');
DEFINE('SECRET_DIANYOU_CHECK_URI'	,	'/cpa_center/user/check.do');


//@海马
DEFINE('SECRET_HAIMA_APPID'			,	'd3220e1c476c1b6d80047245d85bd004');
DEFINE('SECRET_HAIMA_APPKEY'		,	'2172b9bf29ca7cad5b99eca518cbee35');
DEFINE('SECRET_HAIMA_SECRET'		,	'2172b9bf29ca7cad5b99eca518cbee35');
DEFINE('SECRET_HAIMA_CHECK_IP'		,	'api.haimawan.com');
DEFINE('SECRET_HAIMA_CHECK_URI'		,	'/index.php?m=api&a=validate_token');

//@射雕御剑诛仙
DEFINE('SECRET_SHEDIAOYJZX_APPID'			,	'10069');
DEFINE('SECRET_SHEDIAOYJZX_APPKEY'			,	'e116313afb7644e693ee5ac8485cbae0');
DEFINE('SECRET_SHEDIAOYJZX_SECRET'			,	'e116313afb7644e693ee5ac8485cbae0');
DEFINE('SECRET_SHEDIAOYJZX_CHECK_IP'		,	'api.haimawan.com');
DEFINE('SECRET_SHEDIAOYJZX_CHECK_URI'		,	'/index.php?m=api&a=validate_token');

//@天游logincheck OK
DEFINE('SECRET_TIANYOU_APPID'		,	'1009');
DEFINE('SECRET_TIANYOU_APPKEY'		,	'MTAwOSZ0aWFueW91eGkmeGxqLnRpYW55b3V4aS5jb20='  );
DEFINE('SECRET_TIANYOU_CHECK_IP'	,	'www.tianyouxi.com' );
DEFINE('SECRET_TIANYOU_CHECK_URI'	,	'/tianyou/index.php?c=login&a=CheckMember');

//@天游龙剑天下
DEFINE('SECRET_TIANYOULJTX_APPID'			,	'1024');
DEFINE('SECRET_TIANYOULJTX_APPKEY'			,	'MTAyNCZ0aWFueW91eGkmbGp0eC50aWFueW91eGkuY29t');
DEFINE('SECRET_TIANYOULJTX_CHECK_IP'		,	'api.tianyouxi.com');
DEFINE('SECRET_TIANYOULJTX_CHECK_URI'		,	'/index.php/login/XljCheckMember');

//@天游降魔传奇
DEFINE('SECRET_TIANYOUXMCQ_APPID'		,	'1023');
DEFINE('SECRET_TIANYOUXMCQ_APPKEY'		,	'MTAyMyZ0aWFueW91eGkmeG1jcS50aWFueW91eGkuY29t'  );
DEFINE('SECRET_TIANYOUXMCQ_CHECK_IP'	,	'www.tianyouxi.com' );
DEFINE('SECRET_TIANYOUXMCQ_CHECK_URI'	,	'/tianyou/index.php?c=login&a=CheckMember');

//@天游寻龙剑3D
DEFINE('SECRET_TIANYOUXLJ3D_APPID'		,	'1022');
DEFINE('SECRET_TIANYOUXLJ3D_APPKEY'		,	'MTAyMiZ0aWFueW91eGkmeGxqM2QudGlhbnlvdXhpLmNvbQ=='  );
DEFINE('SECRET_TIANYOUXLJ3D_CHECK_IP'	,	'www.tianyouxi.com' );
DEFINE('SECRET_TIANYOUXLJ3D_CHECK_URI'	,	'/tianyou/index.php?c=login&a=CheckMember');

//@闲趣幻城之剑
DEFINE('SECRET_XIANQUHCZJ_CPID'				,	'242');
DEFINE('SECRET_XIANQUHCZJ_APPID'			,	'2');
DEFINE('SECRET_XIANQUHCZJ_APPKEY'			,	'NXdVc2NmTTM=');
DEFINE('SECRET_XIANQUHCZJ_SECRET'			,	'lxEPosSW');
//DEFINE('SECRET_XIANQUHCZJ_CHECK_IP'		,	'null');
//DEFINE('SECRET_XIANQUHCZJ_CHECK_URI'		,	'null');

//@闲趣赤影剑豪
DEFINE('SECRET_XIANQUCYJH_CPID'				,	'242');
DEFINE('SECRET_XIANQUCYJH_APPID'			,	'1');
DEFINE('SECRET_XIANQUCYJH_APPKEY'			,	'NXdVc2NmTTM=');
DEFINE('SECRET_XIANQUCYJH_SECRET'			,	'lxEPosSW');
//DEFINE('SECRET_XIANQUCYJH_CHECK_IP'		,	'null');
//DEFINE('SECRET_XIANQUCYJH_CHECK_URI'		,	'null');

DEFINE('SECRET_TAIQIQL_CPID'				,	'NULL');
DEFINE('SECRET_TAIQIQL_APPID'				,	'NULL');
DEFINE('SECRET_TAIQIQL_APPKEY'				,	'null');
DEFINE('SECRET_TAIQIQL_CHECK_IP'			,	'usdk.taiqigame.com' );
DEFINE('SECRET_TAIQIQL_CHECK_URI'			,	'/channel/');



//@越南版寻龙剑
DEFINE('SECRET_YUENANXLJ_APPKEY'		,	'tuyetthehaokiem');
DEFINE('SECRET_YUENANXLJ_CHECK_IP'		,	'id.vgpjsc.vn' );
DEFINE('SECRET_YUENANXLJ_CHECK_URI'		,	'/18/3/account/authenticate');

DEFINE('SECRET_PANGGAME_PUBKEY'		,	'panggame_rsa_public_key.pem');


DEFINE('SECRET__ONESTORE_APPID'		,	'OA00701135');
DEFINE('SECRET_ONESTORE_STATUS'		,	0);
?>
