<?php
namespace conf
{
DEFINE('WT_PROTOCOL_SCHEDULE',		9999);
DEFINE('WT_PROTOCOL_C_BROADCAST',	1);
DEFINE('WT_PROTOCOL_C_SYSTEM',		2);
DEFINE('WT_PROTOCOL_C_WORLD',		3);
DEFINE('WT_PROTOCOL_C_GROUPS',		4);
DEFINE('WT_PROTOCOL_C_GUILD',		5);
DEFINE('WT_PROTOCOL_C_TEAM',		6);
DEFINE('WT_PROTOCOL_ARENA_FIGHT',	11);
DEFINE('WT_PROTOCOL_MAP_MOVE',		12);
DEFINE('WT_PROTOCOL_FIGHT',		21);
DEFINE('WT_PROTOCOL_DELIVERY',		22);
DEFINE('WT_PROTOCOL_IOS_CHECK',		23);
DEFINE('WT_PROTOCOL_CURL_DEAL',		24);

}
?>
